<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit184bf0e3f84d33c7c4935b82a06e63c9
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit184bf0e3f84d33c7c4935b82a06e63c9::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit184bf0e3f84d33c7c4935b82a06e63c9::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
